spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_cine}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:ConPostgres}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}


server:
  port: ${PORT:8080}